x = 1
y = 1
completed = 0

def updateImage():
    global x
    global y
    global completed

    if completed == 1:
        if x == 1:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 2:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 3:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 4:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
    else:
        if x == 1:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('| * |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   | * |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   | * | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 2:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
<<<<<<< HEAD
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 3:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 4:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')


def playerMovement():
    global x
    global y

    print('\n')
    print('1) Up')
    print('2) Left')
    print('3) Down')
    print('4) Right')
    print('5) Action')

    movement = raw_input('Please insert in your player movement: ')

    if movement == 'w':
        x -= 1
    elif movement == 'a':
        y -= 1
    elif movement == 's':
        x += 1
    elif movement == 'd':
        y += 1
=======
              print(' ___ ___ ___ ___')
              print('|   |   |   |   |')
              print('|   |   |   | * |')
              print('|___|___|___|___|')
              print('|   |   |   |   |')
              print('|   |   |   |   |')
              print('|___|___|___|___|')
              print('|   |   |   |   |')
              print('|   |   |   |   |')
              print('|___|___|___|___|')
>>>>>>> 0d4cc4a050f0414c7d565e99bbf584c59f98c6c4

updateImage()