x = 1
y = 1
completed = 0

def updateImage():
    global x
    global y
    global completed

    if completed == 1:
        if x == 1:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 2:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 2:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   | * |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 3:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   | * |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
            elif y == 4:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   | * |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
        elif x == 3:
            if y == 1:
                print(' ___ ___ ___ ___')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('| * |   |   |   |')
                print('|___|___|___|___|')
                print('|   |   |   |   |')
                print('|   |   |   |   |')
                print('|___|___|___|___|')

updateImage()
